# Generated by Django 4.2.16 on 2024-11-27 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tanaman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField(verbose_name='Absen')),
                ('namaTanam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanaman.tumbuhan')),
            ],
        ),
    ]
